### ISSUE TITLE
The example for the “Forward-Forward Algorithm” in vision examples crashes in TF/Keras version 2.12

### ISSUE THREAD

**Issue by To3No7** [keras-team/keras-io#1191]
I was trying to run the code for “Using the Forward-Forward Algorithm for Image Classification” https://keras.io/examples/vision/forwardforward/ according to https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/forwardforward.ipynb 
This code runs OK in Colab, with version Keras version 2.9, but it crashes when using 
TensorFlow version: 2.12.0-dev20230111
Keras version: 2.12.0

When executing (line 379)
```
model = FFNetwork(dims=[784, 500, 500])
```

It crashes with the following log:
```
Epoch 1/250

2023-01-13 19:29:33.871311: I tensorflow/core/common_runtime/executor.cc:1195] [/device:CPU:0] Executor start aborting: INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_1' with dtype int64 and shape [60000]
	 [[{{node Placeholder/_1}}]]

Training layer 1 now : 
Training layer 2 now : 

---------------------------------------------------------------------------

StagingError                              Traceback (most recent call last)

Cell In[15], line 11
      3 model.compile(
      4     optimizer=keras.optimizers.Adam(learning_rate=0.03),
      5     loss="mse",
      6     jit_compile=True,
      7     metrics=[keras.metrics.Mean()],
      8 )
     10 epochs = 250
---> 11 history = model.fit(train_dataset, epochs=epochs)


File ~/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb


File ~/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py:1199, in func_graph_from_py_func.<locals>.autograph_handler(*args, **kwargs)
   1197 except Exception as e:  # pylint:disable=broad-except
   1198   if hasattr(e, "ag_error_metadata"):
-> 1199     raise e.ag_error_metadata.to_exception(e)
   1200   else:
   1201     raise


StagingError: in user code:

    File "~/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "~/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1249, in run_step  *
        outputs = model.train_step(data)
    File "/tmp/ipykernel_2604/2829577244.py", line 106, in train_step  *
        h_pos, h_neg, loss = layer.forward_forward(h_pos, h_neg)
    File "/tmp/ipykernel_2604/4184424822.py", line 72, in forward_forward  *
        self.optimizer.apply_gradients(zip(gradients, self.dense.trainable_weights))
    File "~/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 213, in _update_step_xla  *
        return self._update_step(gradient, variable)
    File "~/anaconda3/lib/python3.9/site-packages/keras/optimizers/optimizer.py", line 221, in _update_step  **
        raise KeyError(

    KeyError: 'The optimizer cannot recognize variable dense_3/kernel:0. This usually means you are trying to call 
the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the 
full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.Adam.'
```

**Comment by ariG23498** [comment]
@suvadityamuk do you mind taking a look?

**Comment by suvadityamuk** [comment]
Hi, @ariG23498 @To3No7 

I think this issue has been now resolved by #1258 with a change of the optimizer `keras.optimizers.Adam` to `keras.optimizers.legacy.Adam`, but I have not tested the new PR's additions. Please let me know if you think there are any errors, would be happy to investigate.

**Comment by sampathweb** [comment]
Also, if you are testing in TF 2.12, please use RC0, for example in Colab - 
```
!pip install protobuf~=3.2.3
!pip install tensorflow==2.12.0rc0
```

**Comment by suvadityamuk** [comment]
Thank you for the fix, much appreciated, @sampathweb!

**Comment by To3No7** [comment]
Thanks! It now even works with TF-version: 2.13.0-dev20230227
