### ISSUE TITLE
Help needed: convert image_captioning example into tensorflow lite model

### ISSUE THREAD

**Issue by shaunaa126** [keras-team/keras-io#1376]
I need some guidance on how to convert this image_captioning model into a re-usable tensorflow lite model so I can use this model in an Android app for image captioning images taken from the camera.

For reference, this is the full Jupyter notebook: https://gist.github.com/shaunaa126/0ad309208ad1eeb96843e231c121e4b1
The script was taken from here: https://github.com/keras-team/keras-io/blob/master/examples/vision/image_captioning.py (https://keras.io/examples/vision/image_captioning/)

I tried to add tf.function [Signature](https://www.tensorflow.org/guide/function) to the ImageCaptioningModel class, I want the model's default_serving signature to accept an image as an input and spit out the caption as a string:

```python
 @tf.function(input_signature=[tf.TensorSpec(shape=[299, 299, 3], dtype=tf.float32)])
    def call(self, image):
        vocab = vectorization.get_vocabulary()
        index_lookup = dict(zip(range(len(vocab)), vocab))
        max_decoded_sentence_length = SEQ_LENGTH - 1

        # Read the image from the disk
        sample_img = decode_and_resize(image)
        img = sample_img.numpy().clip(0, 255).astype(np.uint8)

        # Pass the image to the CNN
        img = tf.expand_dims(sample_img, 0)
        img = self.cnn_model(img)

        # Pass the image features to the Transformer encoder
        encoded_img = self.encoder(img, training=False)

        # Generate the caption using the Transformer decoder
        decoded_caption = "<start> "
        for i in range(max_decoded_sentence_length):
            tokenized_caption = vectorization([decoded_caption])[:, :-1]
            mask = tf.math.not_equal(tokenized_caption, tf.constant(0))
            predictions = self.decoder(
                tokenized_caption, encoded_img, training=False, mask=mask
            )
            sampled_token_index = np.argmax(predictions[0, i, :])
            sampled_token = index_lookup[sampled_token_index]
            # if sampled_token == "<end>":
            #     break
            # tf.cond(sampled_token == "<end>", lambda: "test", lambda: "continue")
            decoded_caption += " " + sampled_token

        decoded_caption = decoded_caption.replace("<start> ", "")
        decoded_caption = decoded_caption.replace(" <end>", "").strip()
        return {
            "result": decoded_caption
        }
``` 

However when I try to convert the Model from the Keras Model, i get the following error: `OperatorNotAllowedInGraphError: Using a symbolic `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`  I am not familiar with [tf.function](https://www.tensorflow.org/guide/function) and its limitations, any help is appreciated. Below code is what I used to execute converting the model:

```python
# Keras model converter API uses the default signature automatically.
converter = tf.lite.TFLiteConverter.from_keras_model(caption_model)

converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

tflite_model = converter.convert()

# Print the signatures from the converted model
interpreter = tf.lite.Interpreter(model_content=tflite_model)

signatures = interpreter.get_signature_list()
print('Signatures:', signatures)
```

If I can get past the error above, then I can execute the following script to create the Tensorflow lite model:

```python
# Save the model.
with open('model2.tflite', 'wb') as f:
  f.write(tflite_model)

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="model2.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print('Signature:', interpreter.get_signature_list())
print('Input:', input_details)
print('Output:',output_details)
```

**Comment by sachinprasadhs** [comment]
@AakashKumarNain, Could you please help us with the above issue related to your published tutorial here https://keras.io/examples/vision/image_captioning/

**Comment by shaunaa126** [comment]
@AakashKumarNain, let me know if you need any more clarification on this issue. Looking forward to your response.

**Comment by AakashKumarNain** [comment]
Can you please post the full traceback?

**Comment by shaunaa126** [comment]
Does this help? https://gist.github.com/shaunaa126/0ad309208ad1eeb96843e231c121e4b1

**Comment by AakashKumarNain** [comment]
I will look into it today. Thanks

**Comment by shaunaa126** [comment]
Hi @AakashKumarNain, were you able to look into this and hopefully find a solution?

**Comment by AakashKumarNain** [comment]
Couple of things:
1. You need to move these two out of the call function if you want to use `tf.function`
```python
vocab = vectorization.get_vocabulary()
index_lookup = dict(zip(range(len(vocab)), vocab))
```
2. You also have to move the loop outside of the scope of `tf.function`. 

Hope that helps!

**Comment by shaunaa126** [comment]
@AakashKumarNain thanks for the tip. I am not sure how to move these two out of the function as it still results in the same error. If you are saying to completely remove them from the function, how can I return the decoded caption of the image from the function? 

Here is my updated code:

```python
    def vocabfunc(self):
        return vectorization.get_vocabulary()
    
    def index_lookup(self, vocab):
        return dict(zip(range(len(vocab)), vocab))
    
    @tf.function(input_signature=[tf.TensorSpec(shape=[299, 299, 3], dtype=tf.float32)])
    def call(self, image):
        vocab = self.vocabfunc()
        index_lookup = self.index_lookup(vocab)
        max_decoded_sentence_length = SEQ_LENGTH - 1

        # Read the image from the disk
        sample_img = decode_and_resize(image)
        img = sample_img.numpy().clip(0, 255).astype(np.uint8)

        # Pass the image to the CNN
        img = tf.expand_dims(sample_img, 0)
        img = self.cnn_model(img)

        # Pass the image features to the Transformer encoder
        encoded_img = self.encoder(img, training=False)

        # Generate the caption using the Transformer decoder
        decoded_caption = "<start> "
        for i in range(max_decoded_sentence_length):
            tokenized_caption = vectorization([decoded_caption])[:, :-1]
            mask = tf.math.not_equal(tokenized_caption, tf.constant(0))
            predictions = self.decoder(
                tokenized_caption, encoded_img, training=False, mask=mask
            )
            sampled_token_index = np.argmax(predictions[0, i, :])
            sampled_token = index_lookup[sampled_token_index]
            if sampled_token == "<end>":
                break
            # tf.cond(sampled_token == "<end>", lambda: "test", lambda: "continue")
            decoded_caption += " " + sampled_token

        decoded_caption = decoded_caption.replace("<start> ", "")
        decoded_caption = decoded_caption.replace(" <end>", "").strip()
        return {
            "result": decoded_caption
        }
```

Error message 
```
OperatorNotAllowedInGraphError            Traceback (most recent call last)
File [~/miniconda/envs/my-proj/lib/python3.11/site-packages/keras/src/engine/training.py:521](https://file+.vscode-resource.vscode-cdn.net/Users/aa849190/Downloads/github/autopilotai/autopilotai-ml/~/miniconda/envs/my-proj/lib/python3.11/site-packages/keras/src/engine/training.py:521), in Model.build(self, input_shape)
    520 try:
--> 521     self.call(x, **kwargs)
    522 except (tf.errors.InvalidArgumentError, TypeError) as e:

File [~/miniconda/envs/my-proj/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py:153](https://file+.vscode-resource.vscode-cdn.net/Users/aa849190/Downloads/github/autopilotai/autopilotai-ml/~/miniconda/envs/my-proj/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py:153), in filter_traceback..error_handler(*args, **kwargs)
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:

File [~/miniconda/envs/my-proj/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py:52](https://file+.vscode-resource.vscode-cdn.net/Users/aa849190/Downloads/github/autopilotai/autopilotai-ml/~/miniconda/envs/my-proj/lib/python3.11/site-packages/tensorflow/python/eager/polymorphic_function/autograph_util.py:52), in py_func_from_autograph..autograph_handler(*args, **kwargs)
     51 if hasattr(e, "ag_error_metadata"):
---> 52   raise e.ag_error_metadata.to_exception(e)
     53 else:

OperatorNotAllowedInGraphError: in user code:

    File "[/var/folders/2b/p4gxgkbj4qlg9wgcqphy88sw0000gq/T/ipykernel_9013/4198633898.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/2b/p4gxgkbj4qlg9wgcqphy88sw0000gq/T/ipykernel_9013/4198633898.py)", line 283, in call  *
        vocab = self.vocabfunc()
    File "[/var/folders/2b/p4gxgkbj4qlg9wgcqphy88sw0000gq/T/ipykernel_9013/4198633898.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/2b/p4gxgkbj4qlg9wgcqphy88sw0000gq/T/ipykernel_9013/4198633898.py)", line 276, in vocabfunc  *
        return vectorization.get_vocabulary()
    File "[/Users/aa849190/miniconda/envs/my-proj/lib/python3.11/site-packages/keras/src/layers/preprocessing/text_vectorization.py](https://file+.vscode-resource.vscode-cdn.net/Users/aa849190/miniconda/envs/my-proj/lib/python3.11/site-packages/keras/src/layers/preprocessing/text_vectorization.py)", line 493, in get_vocabulary  **
        return self._lookup_layer.get_vocabulary(include_special_tokens)
...
    File "[/Users/aa849190/miniconda/envs/my-proj/lib/python3.11/site-packages/keras/src/layers/preprocessing/index_lookup.py](https://file+.vscode-resource.vscode-cdn.net/Users/aa849190/miniconda/envs/my-proj/lib/python3.11/site-packages/keras/src/layers/preprocessing/index_lookup.py)", line 382, in get_vocabulary
        if self.lookup_table.size() == 0:

    OperatorNotAllowedInGraphError: Using a symbolic `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
.
```

**Comment by AakashKumarNain** [comment]
The `vocabfunc`, and the `index_lookup` are still part of the `tf.function`. You need to separate them completely from the `call` method
