### ISSUE TITLE
Incompatible shapes: [3,8,50,50] vs. [3,3,50,50]

### ISSUE THREAD

**Issue by Jalilnkh** [keras-team/keras-io#1384]
I am using code "English-to-Spanish translation with a sequence-to-sequence Transformer" to train in another language. English to Arabic. 
Why do you think this error occurred?
 
I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: Incompatible shapes: [3,8,50,50] vs. [3,3,50,50]
         [[{{node gradient_tape/transformer/transformer_encoder/multi_head_attention/softmax/add/BroadcastGradientArgs}}]]
Traceback (most recent call last):
  File "/home/train.py", line 233, in <module>
    transformer.fit(train_ds, epochs=epochs, validation_data=val_ds)
  File "/home/venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/venv/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node 'gradient_tape/transformer/transformer_encoder/multi_head_attention/softmax/add/BroadcastGradientArgs' defined at (most recent call last):
    File "/home/train.py", line 233, in <module>
      transformer.fit(train_ds, epochs=epochs, validation_data=val_ds)
    File "/home/venv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/venv/lib/python3.10/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/venv/lib/python3.10/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/home//venv/lib/python3.10/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home//venv/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "/home/venv/lib/python3.10/site-packages/keras/engine/training.py", line 1054, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/home/venv/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 542, in minimize
      grads_and_vars = self.compute_gradients(loss, var_list, tape)
    File "/home/venv/lib/python3.10/site-packages/keras/optimizers/optimizer.py", line 275, in compute_gradients
      grads = tape.gradient(loss, var_list)
Node: 'gradient_tape/transformer/transformer_encoder/multi_head_attention/softmax/add/BroadcastGradientArgs'
Incompatible shapes: [3,8,50,50] vs. [3,3,50,50]
         [[{{node gradient_tape/transformer/transformer_encoder/multi_head_attention/softmax/add/BroadcastGradientArgs}}]] [Op:__inference_train_function_21102]
2023-05-22 16:35:46.431319: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Comment by SuryanarayanaY** [comment]
Hi @Jalilnkh ,

I have executed the attached colab tutorial on tf-nightly and I couldn't found any error.Please refer to attached logs.

I need confirmation whether the reported behaviour arises from the same colab link attached above or whether you are using customized code. If so could you please submit the minimal code snippet required.

If you are using tf.data for pipeline whether the warning log is useful ?

```
This can happen if you have an input pipeline similar to dataset.cache().take(k).repeat(). 
You should use dataset.take(k).cache().repeat() instead.
```

Also if you are using `dataset.batch()` method can you test by passing `drop_reminder=True` ? For me it seems to be problem related to batching.But without code snippet I can't confirm anything.

Thanks!
