### ISSUE TITLE
Efficient Object Detection with YOLOV8 and KerasCV training issue

### ISSUE THREAD

**Issue by Paryavi** [keras-team/keras-io#1475]
I get this error in Colab Pro, after training for one epoch on kerasCV YoloV8 example;
 https://keras.io/examples/vision/yolov8/ 

Epoch 1/3
1271/1271 [==============================] - ETA: 0s - loss: 21.5977 - box_loss: 2.6112 - class_loss: 18.9865
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
[<ipython-input-19-8e8737ecac83>](https://localhost:8080/#) in <cell line: 1>()
----> 1 yolo.fit(
      2     train_ds,
      3     validation_data=val_ds,
      4     epochs=3,
      5     callbacks=[EvaluateCOCOMetricsCallback(val_ds, "model.h5")],

1 frames
[<ipython-input-18-7912382cbc33>](https://localhost:8080/#) in on_epoch_end(self, epoch, logs)
     18             self.metrics.update_state(y_true, y_pred)
     19 
---> 20         metrics = self.metrics.result(force=True)
     21         logs.update(metrics)
     22 

UnknownError: {{function_node __wrapped__EagerPyFunc_Tin_1_Tout_1_device_/job:localhost/replica:0/task:0/device:CPU:0}} InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_317_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Dimension 1 in both shapes must be equal: shape[0] = [4,2,4] vs. shape[1] = [4,1,4] [Op:ConcatV2] name: concat
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/script_ops.py", line 265, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/script_ops.py", line 143, in __call__
    outputs = self._call(device, args)

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/script_ops.py", line 150, in _call
    ret = self._func(*args)

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.10/dist-packages/keras_cv/metrics/object_detection/box_coco_metrics.py", line 203, in result_on_host_cpu
    return tf.constant(obj_result(force), obj.dtype)

  File "/usr/local/lib/python3.10/dist-packages/keras_cv/metrics/object_detection/box_coco_metrics.py", line 254, in result
    self._cached_result = self._compute_result()

  File "/usr/local/lib/python3.10/dist-packages/keras_cv/metrics/object_detection/box_coco_metrics.py", line 262, in _compute_result
    _box_concat(self.ground_truths),

  File "/usr/local/lib/python3.10/dist-packages/keras_cv/metrics/object_detection/box_coco_metrics.py", line 44, in _box_concat
    result[key] = tf.concat([b[key] for b in boxes], axis=0)

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None

  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 7262, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_317_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Dimension 1 in both shapes must be equal: shape[0] = [4,2,4] vs. shape[1] = [4,1,4] [Op:ConcatV2] name: concat

 [Op:EagerPyFunc]

**Comment by Paryavi** [comment]
Colab AI suggests this;

Colab AI
The error is coming from the keras_cv.metrics.object_detection.box_coco_metrics module. The _box_concat function is expecting two tensors with the same shape, but the shapes of the tensors in your input are not the same. The first tensor has a shape of [4, 2, 4], while the second tensor has a shape of [4, 1, 4].

To fix this error, you need to make sure that the two tensors have the same shape. One way to do this is to use the tf.expand_dims function to add a new dimension to the second tensor. For example, you could use the following code:

 
tf.expand_dims(val_ds, axis=1)
[Use code with caution](https://g.co/legal/generative-code)
This will add a new dimension to the second tensor, making it have the same shape as the first tensor. Once you have done this, you should be able to run the yolo.fit function without any errors.

**Comment by meinternational** [comment]
You can avoid the problem by not using `RaggedTensorSpec` for `'boxes'` and `'classes'`. Therefore, replace:
```python
def dict_to_tuple(inputs):
    return inputs["images"], inputs["bounding_boxes"]
````
with (or similar):
```python
def dict_to_tuple(inputs):
    return inputs["images"], bounding_box.to_dense(
        inputs["bounding_boxes"], max_boxes=32
    )
```
in the example code: https://keras.io/examples/vision/yolov8/

**Comment by GaelMusoya** [comment]
> You can avoid the problem by not using `RaggedTensorSpec` for `'boxes'` and `'classes'`. Therefore, replace:
> 
> ```python
> def dict_to_tuple(inputs):
>     return inputs["images"], inputs["bounding_boxes"]
> ```
> 
> with (or similar):
> 
> ```python
> def dict_to_tuple(inputs):
>     return inputs["images"], bounding_box.to_dense(
>         inputs["bounding_boxes"], max_boxes=32
>     )
> ```
> 
> in the example code: https://keras.io/examples/vision/yolov8/

I tried the above but i got another error bellow:

```cmd
1169/1169 [==============================] - ETA: 0s - loss: 15.8625 - box_loss: 1.4815 - class_loss: 14.3810
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[<ipython-input-27-11914d33f4de>](https://localhost:8080/#) in <cell line: 1>()
----> 1 yolo.fit(
      2     train_ds,
      3     validation_data=val_ds,
      4     epochs=1,
      5     callbacks=[EvaluateCOCOMetricsCallback(val_ds, f"{MODEL_PATH}/model.h5")],

1 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51   try:
     52     ctx.ensure_initialized()
---> 53     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                         inputs, attrs, num_outputs)
     55   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

Detected at node 'yolov8_label_encoder_1/cond/GatherV2' defined at (most recent call last):
    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
      app.start()
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
      self._run_once()
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
      handle._run()
    File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
      self.ctx_run(self.run)
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
      self.do_execute(
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
      yielded = ctx_run(next, result)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-27-11914d33f4de>", line 1, in <cell line: 1>
      yolo.fit(
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1791, in fit
      val_logs = self.evaluate(
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2200, in evaluate
      logs = test_function_runner.run_step(
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 4000, in run_step
      tmp_logs = self._function(dataset_or_iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1972, in test_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1956, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1944, in run_step
      outputs = model.test_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/models/object_detection/yolo_v8/yolo_v8_detector.py", line 526, in test_step
      return super().test_step(*args, (x, y))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1852, in test_step
      self.compute_loss(x, y, y_pred, sample_weight)
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/models/object_detection/yolo_v8/yolo_v8_detector.py", line 549, in compute_loss
      target_bboxes, target_scores, fg_mask = self.label_encoder(
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py", line 1150, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/models/object_detection/yolo_v8/yolo_v8_label_encoder.py", line 253, in call
      lambda: (
    File "/usr/local/lib/python3.10/dist-packages/keras_core/src/backend/tensorflow/core.py", line 151, in cond
      return tf.cond(pred, true_fn=true_fn, false_fn=false_fn)
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/models/object_detection/yolo_v8/yolo_v8_label_encoder.py", line 253, in call
      lambda: (
    File "/usr/local/lib/python3.10/dist-packages/keras_cv/models/object_detection/yolo_v8/yolo_v8_label_encoder.py", line 92, in assign
      bbox_scores = ops.take_along_axis(
    File "/usr/local/lib/python3.10/dist-packages/keras_core/src/backend/tensorflow/numpy.py", line 557, in take_along_axis
      return tfnp.take_along_axis(x, indices, axis=axis)
Node: 'yolov8_label_encoder_1/cond/GatherV2'
indices[12600,1] = 2 is not in [0, 2)
	 [[{{node yolov8_label_encoder_1/cond/GatherV2}}]] [Op:__inference_test_function_83405]
```

Any suggestions?
I'm running detection training for 2 objects on the nano yolo model

**Comment by GaelMusoya** [comment]
I had the same problem, in my case all I had to do it manually find corrupted images in my dataset an delete them. I tried writing the script for finding them, but it was not that good with other type of corruption that are visible only when viewing the image

**Comment by Paryavi** [comment]
Thanks, guys for the tips, I did same as I explained in a different thread;
so not using ragged tensor also using PyCOCOCallback;
https://github.com/keras-team/keras-cv/issues/2025#issuecomment-1698399022

**Comment by timoffenhaeusser** [comment]
This helped me a lot! I had the same issue and I solved it by changing the ```dict_to_tuple``` function like @meinternational said. For ```max_boxes=``` I just used the number of boxes every one of my images has (In my case all images have the exact same number of boxes/objects). 

And then I just needed to do ```pip install pycocotools```.

And problem was solved.

**Comment by Jordan-Karangala** [comment]
> You can avoid the problem by not using `RaggedTensorSpec` for `'boxes'` and `'classes'`. Therefore, replace:
> 
> def dict_to_tuple(inputs):
>     return inputs["images"], inputs["bounding_boxes"]
> with (or similar):
> 
> def dict_to_tuple(inputs):
>     return inputs["images"], bounding_box.to_dense(
>         inputs["bounding_boxes"], max_boxes=32
>     )
> in the example code: https://keras.io/examples/vision/yolov8/

Thank you very much, I had the similar issue which is resolved by replacing with the new function.

Thank you.
