### ISSUE TITLE
Question Answer

### ISSUE THREAD

**Issue by reddyprasade** [keras-team/keras-io#1558]
We have Issues with 

https://github.com/keras-team/keras-io/blob/master/examples/nlp/question_answering.py

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
[d:\Saurabh](file:///D:/Saurabh) Singh\question_answering.ipynb Cell 16 line 1
----> [1](vscode-notebook-cell:/d%3A/Saurabh%20Singh/question_answering.ipynb#X21sZmlsZQ%3D%3D?line=0) model.fit(train_set, validation_data=validation_set, epochs=1)

File [c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py:70](file:///C:/Users/EsambatiReddyPrasad/AppData/Local/Programs/Python/Python38/lib/site-packages/keras/src/utils/traceback_utils.py:70), in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File [c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py:53](file:///C:/Users/EsambatiReddyPrasad/AppData/Local/Programs/Python/Python38/lib/site-packages/tensorflow/python/eager/execute.py:53), in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     51 try:
     52   ctx.ensure_initialized()
---> 53   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     54                                       inputs, attrs, num_outputs)
     55 except core._NotOkStatusException as e:
     56   if name is not None:

InvalidArgumentError: Graph execution error:

Detected at node 'tf_distil_bert_for_question_answering/distilbert/embeddings/Gather_1' defined at (most recent call last):
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\traitlets\config\application.py", line 1051, in launch_instance
      app.start()
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelapp.py", line 736, in start
      self.io_loop.start()
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\tornado\platform\asyncio.py", line 195, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
      self._run_once()
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
      handle._run()
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 516, in dispatch_queue
      await self.process_one()
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 505, in process_one
      await dispatch(*args)
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 412, in dispatch_shell
      await result
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelbase.py", line 740, in execute_request
      reply_content = await reply_content
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
      res = shell.run_cell(
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\ipykernel\zmqshell.py", line 546, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py", line 3009, in run_cell
      result = self._run_cell(
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py", line 3064, in _run_cell
      result = runner(coro)
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py", line 3269, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py", line 3448, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "C:\Users\EsambatiReddyPrasad\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\EsambatiReddyPrasad\AppData\Local\Temp\ipykernel_17732\1109371221.py", line 1, in <module>
      model.fit(train_set, validation_data=validation_set, epochs=1)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\training.py", line 1742, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\training.py", line 1338, in train_function
      return step_function(self, iterator)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\training.py", line 1322, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\training.py", line 1303, in run_step
      outputs = model.train_step(data)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\modeling_tf_utils.py", line 1638, in train_step
      y_pred = self(x, training=True)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\training.py", line 569, in __call__
      return super().__call__(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\base_layer.py", line 1150, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\modeling_tf_utils.py", line 947, in run_call_with_unpacked_inputs
      symbolic_weight_name = symbolic_weight_name[:-12] + "weight:0"
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\models\distilbert\modeling_tf_distilbert.py", line 960, in call
      distilbert_output = self.distilbert(
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\base_layer.py", line 1150, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\modeling_tf_utils.py", line 947, in run_call_with_unpacked_inputs
      symbolic_weight_name = symbolic_weight_name[:-12] + "weight:0"
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\models\distilbert\modeling_tf_distilbert.py", line 402, in call
      embedding_output = self.embeddings(input_ids, inputs_embeds=inputs_embeds)  # (bs, seq_length, dim)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\engine\base_layer.py", line 1150, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\src\utils\traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\EsambatiReddyPrasad\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\models\distilbert\modeling_tf_distilbert.py", line 122, in call
      position_embeds = tf.gather(params=self.position_embeddings, indices=position_ids)
Node: 'tf_distil_bert_for_question_answering/distilbert/embeddings/Gather_1'
indices[0,992] = 992 is not in [0, 512)
	 [[{{node tf_distil_bert_for_question_answering/distilbert/embeddings/Gather_1}}]] [Op:__inference_train_function_28978]

**Comment by sachinprasadhs** [comment]
Hi, Thanks for reporting the issue.

I was able to run the tutorial without any error using colab which uses Tensorflow 2.14 version, here https://gist.github.com/sachinprasadhs/3097f0dc09e8e79ea9b22d94e6d34828 is the Gist attached for reference. Thanks!
