### ISSUE TITLE
Error when fitting the model

### ISSUE THREAD

**Issue by Arwa-97** [keras-team/keras-io#1593]
I have an error when fitting the model as shown in the pic. 
Can someone help me how to fix it or what is the issue ?

<img width="1373" alt="code" src="https://github.com/keras-team/keras-io/assets/60826257/28f59c64-57fe-4f56-b8fb-e42cc69e10fd">
<img width="1363" alt="error" src="https://github.com/keras-team/keras-io/assets/60826257/f0519092-3436-462d-b3fd-dd902184c5d4">

Note: I installed the kerasCV by running this command (!pip install git+https://github.com/keras-team/keras-cv -q)

**Comment by sachinprasadhs** [comment]
Could you please provide sample reproducible code to replicate the reported behavior. Thanks!

**Comment by Arwa-97** [comment]
@sachinprasadhs 
here's [colab](https://drive.google.com/file/d/1aNCggY7xGM5Xkse5AcFT3KbR7LSQ7ZbN/view?usp=sharing)

**Comment by sachinprasadhs** [comment]
I have an pending PR which needs to be merged, 

till then could you please apply the changes mentioned in this PR https://github.com/keras-team/keras-io/pull/1556/files#diff-b530d40b01726b3faad1e31c89f0046a4322fac5944abbc97f239a22f43e934a and let us know the outcome. Thanks!

**Comment by Arwa-97** [comment]
Thank you for your respond.
Now I'm getting the following error after I applied the changes from the PR you provided.

[colab](https://drive.google.com/file/d/1aNCggY7xGM5Xkse5AcFT3KbR7LSQ7ZbN/view?usp=sharing)

WARNING:tensorflow:From /usr/local/lib/python3.10/dist-packages/tensorflow/python/util/deprecation.py:660: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
[<ipython-input-11-621bb3a51dce>](https://localhost:8080/#) in <cell line: 9>()
      7     mode="min",
      8 )
----> 9 diffusion_ft_trainer.fit(training_dataset, epochs=epochs, callbacks=[ckpt_callback])

1 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/execute.py](https://localhost:8080/#) in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58         for t in inputs
     59     ]
---> 60     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     61                                         inputs, attrs, num_outputs)
     62   except core._NotOkStatusException as e:

ResourceExhaustedError: Graph execution error:

Detected at node model/resnet_block/group_normalization/weighted_moments/weighted_input_sum defined at (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main

  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code

  File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>

  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start

  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start

  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever

  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once

  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>

  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request

  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute

  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes

  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code

  File "<ipython-input-11-621bb3a51dce>", line 9, in <cell line: 9>

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1783, in fit

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1377, in train_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1360, in step_function

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 1349, in run_step

  File "<ipython-input-9-c61c5f80faa2>", line 31, in train_step

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 589, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py", line 515, in call

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/functional.py", line 672, in _run_internal_graph

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras_cv/models/stable_diffusion/__internal__/layers/resnet_block.py", line 38, in call

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/base_layer.py", line 1149, in __call__

  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 96, in error_handler

  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/group_normalization.py", line 182, in call

  File "/usr/local/lib/python3.10/dist-packages/keras/src/layers/normalization/group_normalization.py", line 214, in _apply_normalization

OOM when allocating tensor with shape[4,32,65536,4] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/resnet_block/group_normalization/weighted_moments/weighted_input_sum}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_242822]

**Comment by sachinprasadhs** [comment]
This OOM error is due to the system GPU memory availability, as mentioned in the tutorial, make sure you have 24-30 GB GPU memory to run this example.

**Comment by Arwa-97** [comment]
Thank you so much!
