### ISSUE TITLE
[example/nlp] Replace tokenizer from pretrain in keras_nlp_tokenizers got error

### ISSUE THREAD

**Issue by Mingbo-Lee** [keras-team/keras-io#1667]
### Issue Type

Bug

### Source

source

### Keras Version

Keras 2.13.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04.5 LTS

### Python version

3.8.18

### GPU model and memory

CPU/378GB

### Current Behavior?

After I run the example [GPT text generation from scratch with KerasNLP](https://keras.io/examples/generative/text_generation_gpt/) in my computer, I want to replace the tokenizer in the scipt from [keras_nlp/tokenizers](https://keras.io/api/keras_nlp/tokenizers/) to realize my design. However, I got error;
I also check the size of the train dataset using:
```python
features = iter(train_ds).next()
features[0].shape
```
all output of them was `TensorShape([64, 128])` , when batch_size was set to 64.
What I want to do is replacing the tokenizer  in the script with the pretrain tokenizer.
I could not solve this problem by myself, so I open this issue for help.

### Standalone code to reproduce the issue or tutorial link

```shell
import os
import keras_nlp
import keras

import tensorflow.data as tf_data
import tensorflow.strings as tf_strings

# Data
BATCH_SIZE = 64
MIN_STRING_LEN = 512  # Strings shorter than this will be discarded
SEQ_LEN = 128  # Length of training sequences, in tokens

# Model
EMBED_DIM = 256
FEED_FORWARD_DIM = 128
NUM_HEADS = 3
NUM_LAYERS = 2
# VOCAB_SIZE = 5000  # Limits parameters in model.

# Training
EPOCHS = 5

# Inference
NUM_TOKENS_TO_GENERATE = 80

keras.utils.get_file(
    origin="https://dldata-public.s3.us-east-2.amazonaws.com/simplebooks.zip",
    extract=True,
)
dir = os.path.expanduser("~/.keras/datasets/simplebooks/")

# Load simplebooks-92 train set and filter out short lines.
raw_train_ds = (
    tf_data.TextLineDataset(dir + "simplebooks-92-raw/train.txt")
    .filter(lambda x: tf_strings.length(x) > MIN_STRING_LEN)
    .batch(BATCH_SIZE)
    .shuffle(buffer_size=256)
)

# Load simplebooks-92 validation set and filter out short lines.
raw_val_ds = (
    tf_data.TextLineDataset(dir + "simplebooks-92-raw/valid.txt")
    .filter(lambda x: tf_strings.length(x) > MIN_STRING_LEN)
    .batch(BATCH_SIZE)
)

tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_base_en")
vocab = tokenizer.get_vocabulary()

vocab_size = len(vocab)
gpt2_preprocessor = keras_nlp.models.GPT2Preprocessor(tokenizer, sequence_length=SEQ_LEN, add_start_token=False, add_end_token=False)

VOCAB_SIZE = len(vocab)


start_packer = keras_nlp.layers.StartEndPacker(
    sequence_length=SEQ_LEN,
    start_value=tokenizer.token_to_id("<|endoftext|>"),
)

def preprocess(inputs):
    outputs = tokenizer(inputs)
    features = start_packer(outputs)
    labels = outputs
    return features, labels

# Tokenize and split into train and label sequences.
train_ds = raw_train_ds.map(preprocess, num_parallel_calls=tf_data.AUTOTUNE).prefetch(
    tf_data.AUTOTUNE
)
val_ds = raw_val_ds.map(preprocess, num_parallel_calls=tf_data.AUTOTUNE).prefetch(
    tf_data.AUTOTUNE
)

inputs = keras.layers.Input(shape=(None,), dtype="int32")
# Embedding.
embedding_layer = keras_nlp.layers.TokenAndPositionEmbedding(
    vocabulary_size=VOCAB_SIZE,
    sequence_length=SEQ_LEN,
    embedding_dim=EMBED_DIM,
    mask_zero=True,
)
x = embedding_layer(inputs)
# Transformer decoders.
for _ in range(NUM_LAYERS):
    decoder_layer = keras_nlp.layers.TransformerDecoder(
        num_heads=NUM_HEADS,
        intermediate_dim=FEED_FORWARD_DIM,
    )
    x = decoder_layer(x)  # Giving one argument only skips cross-attention.
# Output.
outputs = keras.layers.Dense(VOCAB_SIZE)(x)
model = keras.Model(inputs=inputs, outputs=outputs)
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
perplexity = keras_nlp.metrics.Perplexity(from_logits=True, mask_token_id=tokenizer.token_to_id("!"))
model.compile(optimizer="adam", loss=loss_fn, metrics=[perplexity])

model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS)
```

### Relevant log output

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/limingbo/projects/GPT2/text_genration_gpt_pretrain_tokenizer.ipynb 单元格 16 line 9
     95 perplexity = keras_nlp.metrics.Perplexity(from_logits=True, mask_token_id=tokenizer.token_to_id("!"))
     96 model.compile(optimizer="adam", loss=loss_fn, metrics=[perplexity])
---> 98 model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS)

File ~/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /tmp/__autograph_generated_fileguxsxbh3.py:15, in outer_factory.<locals>.inner_factory.<locals>.tf__train_function(iterator)
     13 try:
     14     do_return = True
---> 15     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16 except:
     17     do_return = False

AttributeError: in user code:

    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/engine/training.py", line 1338, in train_function  *
        return step_function(self, iterator)
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/engine/training.py", line 1322, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/engine/training.py", line 1303, in run_step  **
        outputs = model.train_step(data)
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/engine/training.py", line 1081, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/engine/training.py", line 1139, in compute_loss
        return self.compiled_loss(
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/engine/compile_utils.py", line 265, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/losses.py", line 142, in __call__
        losses = call_fn(y_true, y_pred)
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/losses.py", line 268, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/losses.py", line 2385, in _ragged_tensor_sparse_categorical_crossentropy
        return _ragged_tensor_apply_loss(fn, y_true, y_pred, y_pred_extra_dim=True)
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/losses.py", line 1686, in _ragged_tensor_apply_loss
        nested_splits_list = [rt.nested_row_splits for rt in (y_true, y_pred)]
    File "/home/limingbo/anaconda3/envs/limingbo_sf/lib/python3.8/site-packages/keras/src/losses.py", line 1686, in <listcomp>
        nested_splits_list = [rt.nested_row_splits for rt in (y_true, y_pred)]

    AttributeError: 'Tensor' object has no attribute 'nested_row_splits'
```

**Comment by sachinprasadhs** [comment]
I was able to reproduce the error, attaching the Gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/b638bf24f22b21493457f863e3e71ebb/1667.ipynb) for reference. Thanks!

**Comment by Mingbo-Lee** [comment]
Thaks you for replying and review this issue! I have attached the Gist for reference. Please check your Colab notebook again.

**Comment by haifeng-jin** [comment]
@mattdangerw Would you like to take a look?

Thanks!

**Comment by maitry63** [comment]
Hi @Mingbo-Lee, I tried with latest KerasHub &  it is not reproducible. After updating the preprocessing and TensorFlow data loading pipeline, the same GPT architecture runs correctly on the latest KerasHub.

You can try this script with latest KerasHub version which works fine:-

```
import os
import tensorflow as tf
import keras
import keras_hub

# Data
BATCH_SIZE = 64
MIN_STRING_LEN = 512  # Strings shorter than this will be discarded
SEQ_LEN = 128  # Length of training sequences, in tokens

# Model
EMBED_DIM = 256
FEED_FORWARD_DIM = 128
NUM_HEADS = 3
NUM_LAYERS = 2
# VOCAB_SIZE = 5000  # Limits parameters in model.

# Training
EPOCHS = 5

# Inference
NUM_TOKENS_TO_GENERATE = 80

dataset_path = keras.utils.get_file(
    origin="https://dldata-public.s3.us-east-2.amazonaws.com/simplebooks.zip",
    extract=True,
)

dataset_root = os.path.dirname(dataset_path)

print("Dataset extracted at:", dataset_root)

train_file = None
val_file = None

for root, dirs, files in os.walk(dataset_root):
    for file in files:
        if file == "train.txt":
            train_file = os.path.join(root, file)
        elif file == "valid.txt":
            val_file = os.path.join(root, file)

print("Train file:", train_file)
print("Validation file:", val_file)

if train_file is None or val_file is None:
    raise FileNotFoundError(
        "Could not locate train.txt or valid.txt after extraction"
    )


raw_train_ds = (
    tf.data.TextLineDataset(train_file)
    .filter(lambda x: tf.strings.length(x) > MIN_STRING_LEN)
    .shuffle(buffer_size=256)
    .batch(BATCH_SIZE)
)

raw_val_ds = (
    tf.data.TextLineDataset(val_file)
    .filter(lambda x: tf.strings.length(x) > MIN_STRING_LEN)
    .batch(BATCH_SIZE)
)

tokenizer = keras_hub.models.GPT2Tokenizer.from_preset(
    "gpt2_base_en"
)

VOCAB_SIZE = tokenizer.vocabulary_size()

bos_id = tokenizer.token_to_id("<|endoftext|>")


packer = keras_hub.layers.StartEndPacker(
    sequence_length=SEQ_LEN + 1,
    start_value=bos_id,
    pad_value=0,
)


def preprocess(text):

    token_ids = tokenizer(text)

    token_ids = packer(token_ids)

    token_ids = tf.cast(token_ids, tf.int32)

    x = token_ids[:, :-1]
    y = token_ids[:, 1:]

    return x, y


train_ds = (
    raw_train_ds
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .prefetch(tf.data.AUTOTUNE)
)


val_ds = (
    raw_val_ds
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .prefetch(tf.data.AUTOTUNE)
)


EMBED_DIM = 256
FEED_FORWARD_DIM = 128
NUM_HEADS = 3
NUM_LAYERS = 2


inputs = keras.Input(
    shape=(SEQ_LEN,),
    dtype="int32"
)


x = keras_hub.layers.TokenAndPositionEmbedding(
    vocabulary_size=VOCAB_SIZE,
    sequence_length=SEQ_LEN,
    embedding_dim=EMBED_DIM,
    mask_zero=False,
)(inputs)


for _ in range(NUM_LAYERS):
    x = keras_hub.layers.TransformerDecoder(
        intermediate_dim=FEED_FORWARD_DIM,
        num_heads=NUM_HEADS,
    )(x)


outputs = keras.layers.Dense(VOCAB_SIZE)(x)


model = keras.Model(
    inputs,
    outputs
)


model.summary()

loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

perplexity = keras_hub.metrics.Perplexity(
    from_logits=True,
    mask_token_id=0,
)
model.compile(
    optimizer="adam",
    loss=loss,
    metrics=[perplexity],
)
model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS)
```

As this issue is not reproducable we can close this issue !
