### ISSUE TITLE
Multi-GPU distributed training with PyTorch

### ISSUE THREAD

**Issue by bouachalazhar** [keras-team/keras-io#1838]
### Issue Type

Documentation Bug

### Source

source

### Keras Version

Keras 3.2.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04.3

### Current Behavior?

```
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
/usr/lib/python3.10/multiprocessing/popen_fork.py:66: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  self.pid = os.fork()
x_train shape: (60000, 28, 28, 1)
---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
[<ipython-input-14-31fe06a97fdd>](https://localhost:8080/#) in <cell line: 1>()
      1 if __name__ == "__main__":
      2     # We use the "fork" method rather than "spawn" to support notebooks
----> 3     torch.multiprocessing.start_processes(
      4         per_device_launch_fn,
      5         args=(num_gpu,),

1 frames
[/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py](https://localhost:8080/#) in join(self, timeout)
    156         msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    157         msg += original_trace
--> 158         raise ProcessRaisedException(msg, error_index, failed_process.pid)
    159 
    160 

ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "<ipython-input-13-9a6bcf1473c9>", line 47, in per_device_launch_fn
    model = get_model()
  File "<ipython-input-9-4d33f81f3022>", line 14, in get_model
    x = keras.layers.Conv2D(filters=12, kernel_size=3, padding="same", use_bias=False)(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 288, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

### Standalone code to reproduce the issue or tutorial link

```shell
https://keras.io/guides/distributed_training_with_torch/
```

**Comment by fabriciorsf** [comment]
I have a similar problem.
I'm using `keras.utils.PyDataset(workers =1, max_queue_size=2, use_multiprocessing=True)` to load data from files.

```python
File "myscript.py", line 316, in train_autonem
    history = self.model_decoder.fit(self.train_inputs,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../myenv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "...../myenv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "...../myenv/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 764, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...../myenv/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 42, in fetch
    data = next(self.dataset_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "...../myenv/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

I used the values to params:
- `batch_size = 64`
- `workers = 1`
- `max_queue_size = 2`
- `use_multiprocessing = True`

Here is the code for the custom `PyDadaset` for an Autoencoder:
```python
import logging
import multiprocessing
import psutil
import pickle

import numpy as np

from scipy.sparse import csr_matrix, issparse

from keras import Model
from keras import backend as K
from keras.layers import Reshape, RepeatVector
from keras.utils import PyDataset
from keras.callbacks import Callback
from keras import ops as keras_ops

LOGGER = logging.getLogger(__name__)

KBEND = None
MAX_WORKERS = multiprocessing.cpu_count()
TIMES_QUEUE_SIZE = 2

USE_CUDA = False
USE_MPS = False
USE_CPU = False

if K.backend() == 'torch':
    import torch as TORCH
    KBEND = TORCH
    USE_CUDA = TORCH.cuda.is_available()
    USE_MPS = TORCH.backends.mps.is_available()
    if USE_CUDA:
        DEVICE = TORCH.device("cuda")
        LOGGER.info(F"GPU driver and CUDA device are enabled and accessible by PyTorch.")
    elif USE_MPS:
        DEVICE = TORCH.device("mps")
        LOGGER.info(F"MPS device is enabled and accessible by PyTorch.")
    else:
        DEVICE = TORCH.device("cpu")
        USE_CPU = True
        LOGGER.info(F"GPU driver and CUDA device are NOT enabled and accessible by PyTorch.")


def sparse2dense(sparse):
    if issparse(sparse[0]):
        func_to_dense = _to_dense
    else:
        func_to_dense = sparse2dense
    return np.asarray([func_to_dense(array) for array in sparse])


def _to_dense(sparse_array):
    return sparse_array.todense() if (sparse_array.shape[0] > 1) else np.asarray(sparse_array.todense())[0, :]


def dense2sparse(dense):
    if (len(dense[0].shape) > 2):
        func_to_sparse = dense2sparse
    else:
        func_to_sparse = csr_matrix
    return np.asarray([func_to_sparse(array) for array in dense])


def save_obj(obj, file_name):
    with open(file_name, 'wb') as file:
        pickle.dump(obj, file)

def load_obj(file_name):
    with open(file_name, 'rb') as file:
        return pickle.load(file)
		
		
def get_num_workers(workers: int = None) -> int:
    if workers is None:
        return None
    if USE_CUDA:
        return 1
    return min(max(1, workers), MAX_WORKERS)


class AutoencoderSequence(PyDataset):
    
    def __init__(self, inputs,
		model_input: Model,
                batch_size: int,
		workers: int = None,
		train_valid_tests: str = None,
		prefix_path_file: str = None,
		verbose: bool = False):
        self.verbose = verbose
        
        if workers is None or workers < 1:
            workers = 1
            use_multiprocessing = False
            max_queue_size = TIMES_QUEUE_SIZE
        else:
            workers = get_num_workers(workers)
            use_multiprocessing = True
            max_queue_size = workers * TIMES_QUEUE_SIZE

        LOGGER.info(f"Using workers = {workers}, max_queue_size = {max_queue_size} " \
                    f"and use_multiprocessing = {use_multiprocessing} for data loading.")
        super().__init__(workers = workers, max_queue_size = max_queue_size,
                         use_multiprocessing = use_multiprocessing)

        TUPLE_TRAIN_VALID_TEST = ("train", "valid", "tests")
        if train_valid_tests is not None and \
            train_valid_tests not in TUPLE_TRAIN_VALID_TEST:
            raise ValueError(f"The param `train_valid_tests` must be in values {TUPLE_TRAIN_VALID_TEST}." \
                             f" Current value: `{train_valid_tests}`.")

        self.inputs = inputs
        self.len_inputs = len(inputs)
        self.shape = (self.len_inputs,) + inputs[0].shape
        self.model_input = model_input
        self.train_valid_tests = "train" if train_valid_tests is None \
                                else train_valid_tests
        
        prefix_path_file = prefix_path_file if prefix_path_file is not None else ""
        
        self.batch_size = batch_size
        self.batch_prefix_file = (f"{prefix_path_file}_{self.train_valid_tests}_len-" \
                                  f"{self.len_inputs}_bSize-{self.batch_size}")
        self._max_steps_per_epoch = self.__len__()
        self.__pikle_batchs__()

    
    def __len__(self):
        return int(keras_ops.ceil(self.len_inputs / float(self.batch_size)))


    def __getitem__(self, idx: int):
        if idx >= self.__len__():
            if self.verbose:
                LOGGER.debug(f"End of sequence at {self.train_valid_tests} data.")
            raise StopIteration
        idx_epoch = idx #(idx + self._base_step_in_epoch) % self._max_steps_per_epoch
        try:
            batch_inputs = self.__get_batch_inputs_infile__(idx_epoch)
        except BaseException as e:
            LOGGER.debug(f"Error in get batch inputs in file: {e}")
            batch_inputs = self.__get_batch_inputs_inmemory__(idx_epoch)
        batch_inputs = sparse2dense(batch_inputs)
        try:
            batch_predicts = self.__get_batch_predicts_infile__(idx_epoch)
        except BaseException as e:
            LOGGER.debug(f"Error in get batch predict in file: {e}")
            batch_predicts = self.__get_batch_predicts_inmemory__(batch_inputs)
        return batch_inputs if (batch_predicts is None) else (batch_inputs, sparse2dense(batch_predicts))
    
	
    def __pikle_batchs__(self, empty_memory: bool = True):
        for idx in range(0, self._max_steps_per_epoch):
            batch_inputs = self.__get_batch_inputs_inmemory__(idx)
            batch_input_file_name = self.__get_batch_input_file_name__(idx)
            batch_predict_file_name = self.__get_batch_predict_file_name__(idx)
            if self.verbose:
                LOGGER.debug(f"Saving batch inputs (idx={idx}) in file: {batch_input_file_name}")
            save_obj(batch_inputs, batch_input_file_name)
            batch_inputs = sparse2dense(batch_inputs)
            batch_predicts = self.__get_batch_predicts_inmemory__(batch_inputs)
            batch_predicts = dense2sparse(batch_predicts)
            if self.verbose:
                LOGGER.debug(f"Saving batch predicts (idx={idx}) in file: {batch_predict_file_name}")
            save_obj(batch_predicts, batch_predict_file_name)
        if empty_memory:
            self.inputs = None
    
	
    def __get_batch_inputs_inmemory__(self, idx: int):
        low = idx * self.batch_size
        high = min(low + self.batch_size, self.len_inputs) #(idx + 1) * self.batch_size
        return self.inputs[low:high]
    
	
    def __get_batch_inputs_infile__(self, idx: int):
        batch_input_file_name = self.__get_batch_input_file_name__(idx)
        if self.verbose:
            LOGGER.debug(f"Loading batch inputs (idx={idx}) from file: {batch_input_file_name}")
        return load_obj(batch_input_file_name)
    
	
    def __get_batch_predicts_inmemory__(self, batch_inputs):
        try:
            return self.model_input.predict(batch_inputs, verbose=0)
        except TypeError:
            return None
    
	
    def __get_batch_predicts_infile__(self, idx: int):
        batch_predict_file_name = self.__get_batch_predict_file_name__(idx)
        if self.verbose:
            LOGGER.debug(f"Loading batch predicts (idx={idx}) from file: {batch_predict_file_name}")
        return load_obj(batch_predict_file_name)
    
	
    def __get_batch_input_file_name__(self, idx: int):
        return self.__get_batch_file_name__(idx, True)
    
	
    def __get_batch_predict_file_name__(self, idx: int):
        return self.__get_batch_file_name__(idx, False)
    
	
    def __get_batch_file_name__(self, idx: int, inputs: bool):
        len_idx_str = len(f"{self._max_steps_per_epoch}")
        inputs_predicts = "inputs" if inputs else "predicts"
        return f"{self.batch_prefix_file}_{inputs_predicts}_idx-%0{len_idx_str}d.pkl" % idx
```

**Comment by phageous01** [comment]
You have to use spawn if you are training on multiple GPUs. The guide, I suspect, was only tested on CPUs.

I followed the guide and wrote PyTorch distributed training over a Keras mode using DDP. I ran into a ton of problems, but eventually made it work. There were lots of device placement mismatch that I had to manually fix. 

While I got it to work, it felt hacky and unstable, and I suggest you either use a native PyTorch model with DDP, or wait for Keras to add the official distributed training support for the Torch backend.
