### ISSUE TITLE
Error Running tfrecord.ipynb In Sagemaker

### ISSUE THREAD

**Issue by lforeman2** [keras-team/keras-io#382]
I have made a few minor modifications to the script for compatibility with AWS/S3/Sagemaker using CPU instead of GPU. Because the you cannot connect to gcs to get the tfrecord files from AWS, I download the tfrecord files from kaggle (https://www.kaggle.com/c/siim-isic-melanoma-classification) and uploaded to my s3 bucket. I use the train014 and train015 files for validation. 
I get stuck with a NoneType error when trying to load the validation dataset:
**ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.**
I get the same error with framework=2.1.0 and py_version=py3. I think it would be nice to have an example of how to run a model on tfrecord files in an AWS environment.

Here is the entrypoint script:
```
import tensorflow as tf
import os
import argparse
import json
from functools import partial

def decode_image(image):
    image = tf.image.decode_jpeg(image, channels=3)
    image = tf.cast(image, tf.float32)
    image = tf.reshape(image, [1024, 1024, 3])
    return image

def read_tfrecord(example, labeled):
    tfrecord_format = (
        {
            "image": tf.io.FixedLenFeature([], tf.string),
            "target": tf.io.FixedLenFeature([], tf.int64),
        }
        if labeled
        else {"image": tf.io.FixedLenFeature([], tf.string),}
    )
    example = tf.io.parse_single_example(example, tfrecord_format)
    image = decode_image(example["image"])
    if labeled:
        label = tf.cast(example["target"], tf.int32)
        return image, label
    return image

def load_dataset(filenames,labeled=True):
    ignore_order = tf.data.Options()
    ignore_order.experimental_deterministic = False  # disable order, increase speed
    dataset = tf.data.TFRecordDataset(
        filenames
    )  # automatically interleaves reads from multiple files
    dataset = dataset.with_options(
        ignore_order
    )  # uses data as soon as it streams in, rather than in its original order
    dataset = dataset.map(
        partial(read_tfrecord, labeled=labeled), num_parallel_calls=tf.data.experimental.AUTOTUNE
    )
    # returns a dataset of (image, label) pairs if labeled=True or just images if labeled=False
    return dataset

def get_dataset(filenames, labeled=True):
    dataset = load_dataset(filenames, labeled=labeled)
    dataset = dataset.shuffle(2048)
    dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    dataset = dataset.batch(64)
    return dataset


def make_model():
    initial_learning_rate = 0.01
    lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
         initial_learning_rate, decay_steps=20, decay_rate=0.96, staircase=True)

    checkpoint_cb = tf.keras.callbacks.ModelCheckpoint(
        "melanoma_model.h5", save_best_only=True)

    early_stopping_cb = tf.keras.callbacks.EarlyStopping(
        patience=10, restore_best_weights=True)

    base_model = tf.keras.applications.Xception(
        input_shape=(1024, 1024, 3), include_top=False, weights=None
    )

    base_model.trainable = False

    inputs = tf.keras.layers.Input([1024, 1024, 3])
    x = tf.keras.applications.xception.preprocess_input(inputs)
    x = base_model(x)
    x = tf.keras.layers.GlobalAveragePooling2D()(x)
    x = tf.keras.layers.Dense(8, activation="relu")(x)
    x = tf.keras.layers.Dropout(0.7)(x)
    outputs = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    model = tf.keras.Model(inputs=inputs, outputs=outputs)

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule),
        loss="binary_crossentropy",
        metrics=tf.keras.metrics.AUC(name="auc"),
    )
    return model

def _load_training_data(train_dir, valid_dir):
    train_dataset = get_dataset(train_dir)
    valid_dataset = get_dataset(valid_dir)
    return train_dataset, valid_dataset

def _parse_args():
    parser = argparse.ArgumentParser()
    # Data, model, and output directories
    # model_dir is always passed in from SageMaker. By default this is a S3 path under the default bucket.
    parser.add_argument('--model_dir', type=str,default=os.environ.get('SM_MODEL_DIR'))
    parser.add_argument('--model_output_dir', type=str,default=os.environ.get('SM_MODEL_DIR'))
    parser.add_argument('--sm-model-dir', type=str, default=os.environ.get('SM_MODEL_DIR'))
    parser.add_argument('--train', type=str, default=os.environ.get('SM_CHANNEL_TRAINING'))
    parser.add_argument('--valid', type=str, default=os.environ.get('SM_CHANNEL_VALIDATION'))
    parser.add_argument('--hosts', type=list, default=json.loads(os.environ.get('SM_HOSTS')))
    parser.add_argument('--current-host', type=str, default=os.environ.get('SM_CURRENT_HOST'))
    return parser.parse_known_args()

if __name__ == "__main__":
    args, unknown = _parse_args()
        
    train_dataset, vaid_dataset=_load_training_data(args.train, args.valid)

    model = make_model()
    model.fit(train_dataset,validation_data=valid_dataset, epochs=2, callbacks=[checkpoint_cb, early_stopping_cb])


    if args.current_host == args.hosts[0]:
        model.save(os.path.join(args.model_dir, '000000001'))

```
Here is the estimator object that I fit:
```
import sagemaker
from sagemaker import get_execution_role
from sagemaker.tensorflow import TensorFlow

training_data_uri='s3://my/path/in/s3/train/'
validation_data_uri='s3://my/path/in/s3/valid/'
role = get_execution_role()

estimator = TensorFlow(entry_point='entrypoint.py',
                             role=role,
                             model_dir='s3://my/path/in/s3/model',
                             instance_count=2,
                             instance_type='ml.m5.xlarge',
                             framework_version='2.2.0',
                             py_version='py37',
                             distribution={'parameter_server': {'enabled': True}})

estimator.fit(training_data_uri, validation_data_uri)
```
Here is the error:
```
Invoking script with the following command:

/usr/local/bin/python3.7 entrypoint.py --model_dir s3://my/path/in/s3/model


2021-02-25 14:59:26,964 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
Command "/usr/local/bin/python3.7 entrypoint.py --model_dir s3://my/path/in/s3/model"
2021-02-25 14:59:24.972755: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:425] Initializing the SageMaker Profiler.
2021-02-25 14:59:24.972877: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:106] SageMaker Profiler is not enabled. The timeline writer thread will not be started, future recorded events will be dropped.
2021-02-25 14:59:24.993425: W tensorflow/core/profiler/internal/smprofiler_timeline.cc:425] Initializing the SageMaker Profiler.
Traceback (most recent call last):
  File "entrypoint.py", line 109, in <module>
    train_dataset=_load_training_data(args.train, args.valid)
  File "entrypoint.py", line 103, in _load_training_data
    valid_dataset = get_dataset(valid_dir, args.buffer_size, args.batch_size)
  File "entrypoint.py", line 37, in get_dataset
    dataset = load_dataset(filenames)
  File "entrypoint.py", line 28, in load_dataset
    dataset = tf.data.TFRecordDataset(filenames)  # automatically interleaves reads from multiple files
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/data/ops/readers.py", line 336, in __init__
    filenames = _create_or_validate_filenames_dataset(filenames)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/data/ops/readers.py", line 56, in _create_or_validate_filenames_dataset
    filenames = ops.convert_to_tensor(filenames, dtype_hint=dtypes.string)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1341, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 321, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 262, in constant
    allow_broadcast=True)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
```

**Comment by sachinprasadhs** [comment]
Hi, 

Could you please point to the source of the tutorial or example you are referring to. 

Also, please update to the latest version and refer the latest code.

For TFRecord examples, refer to the guide here https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/load_data/tfrecord.ipynb
