### ISSUE TITLE
Docker build command does not work

### ISSUE THREAD

**Issue by BerengereMathieu** [keras-team/keras-io#412]
Hello,

I try to run a local copy of the website. 

When launching  docker command `docker build -t keras-io . && docker run --rm -p 8000:8000 keras-io` I have the following error message: 

``` 
...Processing api/layers/attention_layers/multi_head_attention
/usr/local/lib/python3.7/site-packages/sphinx/util/inspect.py:555: RemovedInSphinx40Warning: sphinx.util.inspect.Signature() is deprecated
  RemovedInSphinx40Warning)
Traceback (most recent call last):
  File "/scripts/docstrings.py", line 114, in import_object
    last_object_got = importlib.import_module(".".join(seen_names))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow.keras.layers.MultiHeadAttention'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autogen.py", line 911, in <module>
    keras_io.make_md_sources()
  File "autogen.py", line 106, in make_md_sources
    self.make_md_source_for_entry(self.master, path_stack=[], title_stack=[])
  File "autogen.py", line 509, in make_md_source_for_entry
    self.make_md_source_for_entry(entry, path_stack[:], title_stack[:])
  File "autogen.py", line 509, in make_md_source_for_entry
    self.make_md_source_for_entry(entry, path_stack[:], title_stack[:])
  File "autogen.py", line 509, in make_md_source_for_entry
    self.make_md_source_for_entry(entry, path_stack[:], title_stack[:])
  [Previous line repeated 1 more time]
  File "autogen.py", line 455, in make_md_source_for_entry
    generated_md += self.docstring_printer.render(element)
  File "/scripts/docstrings.py", line 72, in render
    object_ = import_object(element)
  File "/scripts/docstrings.py", line 116, in import_object
    last_object_got = getattr(last_object_got, name)
AttributeError: module 'tensorflow.keras.layers' has no attribute 'MultiHeadAttention'

```
This error may be related to the installed tensorflow version `ARG TF_VERSION=2.3.0`  which does not seem to include `MultiHeadAttention` (as explained here: https://github.com/tensorflow/models/issues/9357)

I attach a log file with all the output.
[error_kerasio.log](https://github.com/keras-team/keras-io/files/6157162/error_kerasio.log)

**Comment by omrylcn** [comment]
when i change  ARG instruction  as TF_VERSION=2.4.0, docker example it works

**Comment by sachinprasadhs** [comment]
Hi, Thanks for reporting the issue.

Could you please try to build again with the latest updated configuration and requirements.

https://github.com/keras-team/keras-io/blob/74c762982f26081292fd0661f1736b72210fcf33/Dockerfile#L1-L10
https://github.com/keras-team/keras-io/blob/74c762982f26081292fd0661f1736b72210fcf33/requirements.txt#L1-L17
