### ISSUE TITLE
Error when using autogen.py add_example command

### ISSUE THREAD

**Issue by BerengereMathieu** [keras-team/keras-io#416]
Hello,

I try adding the following tutobook to my local keras-io project, to understand how to contribute to Keras examples:

```python
"""
Title: Test Example
Author: [Makina Corpus](https://makina-corpus.com)
Date created: 2021/03/19
Last modified: 2021/03/19
Description: Just a test.
"""
"""
# Test example
"""

import tensorflow as tf

print(tf.__version__)

``` 

Command `python autogen.py add_example vision/test_example.py` give me the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d1382151fdd6> in <module>
----> 1 import tensorflow as tf
      2 
      3 print(tf.__version__)

~/anaconda3/lib/python3.8/site-packages/tensorflow/__init__.py in <module>
     39 import sys as _sys
     40 
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43 

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/__init__.py in <module>
     39 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
     40 
---> 41 from tensorflow.python.eager import context
     42 
     43 # pylint: enable=wildcard-import

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/context.py in <module>
     26 import threading
     27 
---> 28 from absl import logging
     29 import numpy as np
     30 import six

ModuleNotFoundError: No module named 'absl'
ModuleNotFoundError: No module named 'absl'

Traceback (most recent call last):
  File "autogen.py", line 916, in <module>
    keras_io.add_example(
  File "autogen.py", line 233, in add_example
    tutobooks.py_to_md(py_path, nb_path, md_path, img_dir, working_dir=working_dir)
  File "/home/berengere/Projects/Contrib/keras-io/scripts/tutobooks.py", line 281, in py_to_md
    nb_to_md(nb_path, md_path, img_dir, working_dir=working_dir)
  File "/home/berengere/Projects/Contrib/keras-io/scripts/tutobooks.py", line 273, in nb_to_md
    raise RuntimeError(
RuntimeError: An error was encountered when attempting to run the notebook. See logs for details.
```

I am working in a virtual env, described in this file:
[env_keras_io.log](https://github.com/keras-team/keras-io/files/6170442/env_keras_io.log)

When launching python interperter, I could load corrrectly tensorflow:
```
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-03-19 11:35:59.953408: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
>>> print(tf.__version__)
2.4.1
```

I have the same issue when directly installing requirement in anaconda base virtual env and running autogen add_example command and when importing tensorflow from local conda python interpreter:

```
(base) ~$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-03-19 11:42:23.117022: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/berengere/anaconda3/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/berengere/anaconda3/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/home/berengere/anaconda3/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from absl import logging
ModuleNotFoundError: No module named 'absl'
>>> 
```

The complete log could be see here:
[error_kerasio_add_example.log](https://github.com/keras-team/keras-io/files/6170449/error_kerasio_add_example.log)

**Comment by SuryanarayanaY** [comment]
Hi @BerengereMathieu ,

Could you please which tutorial you are referring to? 

If you want to add a `example.py` file to another `source.py` file you may use the code like below.

```
%%writefile example.py
<your Code here>
```
Then execute the cell then `example.py` can be added to your `source.py`. Please refer attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/4d900a387454405febdbce35a80aa76b/kerasio_416.ipynb) also for reference.
