### ISSUE TITLE
Cannot generate a local copy of the keras.io website 

### ISSUE THREAD

**Issue by iliachry** [keras-team/keras-io#501]
Hello, I try to generate a local copy of the keras.io website. 

I clone the keras-io repo on my PC and when I run the` python autogen.py make` command I get the following:

> Generating md sources
> Traceback (most recent call last):
>   File "autogen.py", line 913, in <module>
>     keras_io.make_md_sources()
>   File "autogen.py", line 104, in make_md_sources
>     self.sync_tutobook_templates()
>   File "autogen.py", line 333, in sync_tutobook_templates
>     Path(self.guides_dir) / "md", Path(self.templates_dir) / "guides", ext=".md"
>   File "autogen.py", line 753, in copy_inner_contents
>     copy_inner_contents(fpath, fdst, ext)
>   File "autogen.py", line 751, in copy_inner_contents
>     shutil.copyfile(fpath, fdst)
>   File "C:\Users\iliac\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 121, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: '..\\templates\\guides\\keras_tuner\\custom_tuner.md'

**Comment by iliachry** [comment]
Problem solved by using python version 3.9.2 and pip version 21.1.2
