### ISSUE TITLE
Resource exhausted: failed to allocate memory for keras-io/examples/vision/retinanet.py

### ISSUE THREAD

**Issue by sergorl** [keras-team/keras-io#709]
I have `NVIDIA GeForce RTX 2080 Super` and `Windows 10`, `tensorflow==2.5.0`.

When I try to run `keras-io/examples/vision/retinanet.py`, I got this error (first part):

`
2021-11-16 11:33:41.538437: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-16 11:33:42.020381: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5963 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Super, pci bus id: 0000:01:00.0, compute capability: 7.5
2021-11-16 11:33:44.891107: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-11-16 11:33:51.290121: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8100
2021-11-16 11:33:53.139338: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.18GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.139521: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.18GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.147882: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.148045: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.206057: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.206287: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.10GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.242526: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.242699: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.566151: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.22GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:33:53.566340: W tensorflow/core/common_runtime/bfc_allocator.cc:272] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.22GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2021-11-16 11:34:04.164976: W tensorflow/core/common_runtime/bfc_allocator.cc:457] Allocator (GPU_0_bfc) ran out of memory trying to allocate 144.23MiB (rounded to 151240448)requested by op RetinaNetLoss/RetinaNetClassificationLoss/logistic_loss/mul
If the cause is memory fragmentation maybe the environment variable 'TF_GPU_ALLOCATOR=cuda_malloc_async' will improve the situation. 
Current allocation summary follows.
Current allocation summary follows.
2021-11-16 11:34:04.165236: I tensorflow/core/common_runtime/bfc_allocator.cc:1004] BFCAllocator dump for GPU_0_bfc
2021-11-16 11:34:04.165299: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (256): 	Total Chunks: 189, Chunks in use: 189. 47.2KiB allocated for chunks. 47.2KiB in use in bin. 18.8KiB client-requested in use in bin.
2021-11-16 11:34:04.165413: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (512): 	Total Chunks: 80, Chunks in use: 80. 40.0KiB allocated for chunks. 40.0KiB in use in bin. 40.0KiB client-requested in use in bin.
2021-11-16 11:34:04.165522: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (1024): 	Total Chunks: 193, Chunks in use: 193. 195.5KiB allocated for chunks. 195.5KiB in use in bin. 193.0KiB client-requested in use in bin.
2021-11-16 11:34:04.165636: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (2048): 	Total Chunks: 114, Chunks in use: 114. 233.0KiB allocated for chunks. 233.0KiB in use in bin. 229.6KiB client-requested in use in bin.
2021-11-16 11:34:04.165748: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (4096): 	Total Chunks: 71, Chunks in use: 70. 290.0KiB allocated for chunks. 286.0KiB in use in bin. 280.0KiB client-requested in use in bin.
2021-11-16 11:34:04.165859: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (8192): 	Total Chunks: 40, Chunks in use: 40. 330.5KiB allocated for chunks. 330.5KiB in use in bin. 320.0KiB client-requested in use in bin.
2021-11-16 11:34:04.165974: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (16384): 	Total Chunks: 3, Chunks in use: 2. 48.0KiB allocated for chunks. 32.0KiB in use in bin. 32.0KiB client-requested in use in bin.
2021-11-16 11:34:04.166083: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (32768): 	Total Chunks: 2, Chunks in use: 2. 73.5KiB allocated for chunks. 73.5KiB in use in bin. 73.5KiB client-requested in use in bin.
2021-11-16 11:34:04.166191: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (65536): 	Total Chunks: 13, Chunks in use: 12. 1000.5KiB allocated for chunks. 913.8KiB in use in bin. 768.0KiB client-requested in use in bin.
2021-11-16 11:34:04.166300: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (131072): 	Total Chunks: 16, Chunks in use: 16. 2.46MiB allocated for chunks. 2.46MiB in use in bin. 2.31MiB client-requested in use in bin.
2021-11-16 11:34:04.166408: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (262144): 	Total Chunks: 19, Chunks in use: 19. 5.81MiB allocated for chunks. 5.81MiB in use in bin. 5.17MiB client-requested in use in bin.
2021-11-16 11:34:04.166521: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (524288): 	Total Chunks: 23, Chunks in use: 23. 14.13MiB allocated for chunks. 14.13MiB in use in bin. 12.95MiB client-requested in use in bin.
2021-11-16 11:34:04.166633: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (1048576): 	Total Chunks: 26, Chunks in use: 25. 28.12MiB allocated for chunks. 26.73MiB in use in bin. 24.56MiB client-requested in use in bin.
2021-11-16 11:34:04.166750: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (2097152): 	Total Chunks: 51, Chunks in use: 51. 118.72MiB allocated for chunks. 118.72MiB in use in bin. 114.81MiB client-requested in use in bin.
2021-11-16 11:34:04.166859: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (4194304): 	Total Chunks: 28, Chunks in use: 26. 135.90MiB allocated for chunks. 124.62MiB in use in bin. 119.87MiB client-requested in use in bin.
2021-11-16 11:34:04.166970: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (8388608): 	Total Chunks: 42, Chunks in use: 42. 402.92MiB allocated for chunks. 402.92MiB in use in bin. 397.25MiB client-requested in use in bin.
2021-11-16 11:34:04.181787: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (16777216): 	Total Chunks: 28, Chunks in use: 26. 564.78MiB allocated for chunks. 518.46MiB in use in bin. 507.94MiB client-requested in use in bin.
2021-11-16 11:34:04.181896: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (33554432): 	Total Chunks: 37, Chunks in use: 37. 1.39GiB allocated for chunks. 1.39GiB in use in bin. 1.39GiB client-requested in use in bin.
2021-11-16 11:34:04.182001: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (67108864): 	Total Chunks: 9, Chunks in use: 9. 693.00MiB allocated for chunks. 693.00MiB in use in bin. 693.00MiB client-requested in use in bin.
2021-11-16 11:34:04.182113: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (134217728): 	Total Chunks: 16, Chunks in use: 16. 2.51GiB allocated for chunks. 2.51GiB in use in bin. 2.35GiB client-requested in use in bin.
2021-11-16 11:34:04.182220: I tensorflow/core/common_runtime/bfc_allocator.cc:1011] Bin (268435456): 	Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2021-11-16 11:34:04.182317: I tensorflow/core/common_runtime/bfc_allocator.cc:1027] Bin for 144.23MiB was 128.00MiB, Chunk State: 
2021-11-16 11:34:04.182378: I tensorflow/core/common_runtime/bfc_allocator.cc:1040] Next region of size 6252920832
2021-11-16 11:34:04.182437: I tensorflow/core/common_runtime/bfc_allocator.cc:1060] InUse at b0e800000 of size 256 next 1
2021-11-16 11:34:04.182494: I tensorflow/core/common_runtime/bfc_allocator.cc:1060] InUse at b0e800100 of size 1280 next 2
`

final part of error:

`
2021-11-16 11:34:36.221235: I tensorflow/core/common_runtime/bfc_allocator.cc:1072] Sum Total of in-use chunks: 5.79GiB
2021-11-16 11:34:36.221299: I tensorflow/core/common_runtime/bfc_allocator.cc:1074] total_region_allocated_bytes_: 6252920832 memory_limit_: 6252920832 available bytes: 0 curr_region_allocation_bytes_: 12505841664
2021-11-16 11:34:36.221406: I tensorflow/core/common_runtime/bfc_allocator.cc:1080] Stats: 
Limit:                      6252920832
InUse:                      6218702592
MaxInUse:                   6218702592
NumAllocs:                        2348
MaxAllocSize:               1470693376
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0

2021-11-16 11:34:36.221632: W tensorflow/core/common_runtime/bfc_allocator.cc:468] ******************************************************************************************x********x
2021-11-16 11:34:36.221746: W tensorflow/core/framework/op_kernel.cc:1680] Resource exhausted: failed to allocate memory
Traceback (most recent call last):
  File "D:/repositories/flowchart-recognition/retinanet.py", line 877, in <module>
    model.fit(
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\keras\engine\training.py", line 1184, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\function.py", line 591, in call
    outputs = execute.execute(
  File "C:\Users\s00557672\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  failed to allocate memory
	 [[node RetinaNetLoss/RetinaNetClassificationLoss/logistic_loss/mul (defined at D:/repositories/flowchart-recognition/retinanet.py:734) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_15846]

Errors may have originated from an input operation.
Input Source operations connected to node RetinaNetLoss/RetinaNetClassificationLoss/logistic_loss/mul:
 RetinaNetLoss/strided_slice_3 (defined at D:/repositories/flowchart-recognition/retinanet.py:762)	
 RetinaNetLoss/one_hot (defined at D:/repositories/flowchart-recognition/retinanet.py:757)

Function call stack:
train_function
`

**Comment by huzongxiang** [comment]
One reason could be menory of your GPU is not enough to load your dataset, minimize your dataset or increase your menory size using more power GPU device, the other is that your residual task running in your GPU is not killed.

**Comment by SuryanarayanaY** [comment]
@sergorl ,

Resource exhausted error is related Memory resource constraints. It should not be a  problem with keras.

You should have sufficient Memory to load and train the `retinanet` model. Alternatively you can reduce the `batch_size` which needs lower memory compared to higher `batch_size`. For this retinanet example since input is passed as Dataset object `batch_size` is not a valid parameter. You can reduce the dataset size in `model.fit` , for example in the attached example we have `train_dataset.take(1000)` which can be reduced to lower number such as `train_dataset.take(100)` something and can try for execution with required changes.

Thanks!
