### ISSUE TITLE
`ValueError: The model cannot be compiled because it has no loss to optimize.`

### ISSUE THREAD

**Issue by siyuany** [keras-team/keras-io#73]
When I checked the **tutorial** [Customizing what happens in `fit()`](https://github.com/keras-team/keras-io/blob/master/guides/customizing_what_happens_in_fit.py) (really important and please go through this **OFFICIAL** tutorial) and ran the codes, I got the following error:

```
WARNING:tensorflow:Output dense_1 missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to dense_1.
Traceback (most recent call last):
  File "/Users/yaosiyuan/PycharmProjects/tensorflow/adversarial_training/customize.py", line 142, in <module>
    model.compile(optimizer="adam")
  File "/Users/yaosiyuan/.pyenv/versions/anaconda3-5.3.1/envs/tflow_dl/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/yaosiyuan/.pyenv/versions/anaconda3-5.3.1/envs/tflow_dl/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 373, in compile
    self._compile_weights_loss_and_weighted_metrics()
  File "/Users/yaosiyuan/.pyenv/versions/anaconda3-5.3.1/envs/tflow_dl/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/Users/yaosiyuan/.pyenv/versions/anaconda3-5.3.1/envs/tflow_dl/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1653, in _compile_weights_loss_and_weighted_metrics
    self.total_loss = self._prepare_total_loss(masks)
  File "/Users/yaosiyuan/.pyenv/versions/anaconda3-5.3.1/envs/tflow_dl/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1752, in _prepare_total_loss
    raise ValueError('The model cannot be compiled '
ValueError: The model cannot be compiled because it has no loss to optimize.
```

I read the source code of `tf.keras.Model`, I found the class don't have a method called `train_step` and no codes invoking `train_step`. 

Environtment:  

python:  Python 3.7.7
tensorflow: 2.0.0
keras: 2.2.4-tf

**Comment by uditmaherwal** [comment]
try model.compile(loss = '[any loss function]',optimizer='adam')

**Comment by siyuany** [comment]
> try model.compile(loss = '[any loss function]',optimizer='adam')

Yes, of course this can fix the ERROR.

But I doubt actually we **CAN NOT** use the way described by this tutorial to customize the `fit` process. Because there is no member in `keras.Model` called `train_step`, and <del>rewrite</del>  **add** `train_step` method in subclasses can not change `model.fit` behaviors.

This tutorial is post tens of days ago, I wonder whether it is tested.

**Comment by fchollet** [comment]
This tutorial requires TF 2.2 or higher.
