### ISSUE TITLE
Imposible to save model for : bayesian_neural_networks.py

### ISSUE THREAD

**Issue by Martinc4321** [keras-team/keras-io#760]
When i simply do: 
_prob_bnn_model.save('model')_
after the _run_experiment_ was called on _prob_bnn_model_.

[This file](https://github.com/keras-team/keras-io/blob/master/examples/keras_recipes/bayesian_neural_networks.py)

**Then I am getting error message:**
Traceback (most recent call last):
  File "gitCopy.py", line 403, in <module>
    prob_bnn_model.save("asdasd")
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/conto/.local/lib/python3.8/site-packages/tensorflow_probability/python/layers/distribution_layer.py", line 220, in __call__
    distribution, _ = super(DistributionLambda, self).__call__(
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.

**When i try to save it in H5 format then message is:**
Traceback (most recent call last):
  File "gitCopy.py", line 403, in <module>
    prob_bnn_model.save("asdasd.h5")
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py", line 746, in get_config
    raise NotImplementedError(textwrap.dedent(f"""
NotImplementedError: 
Layer DenseVariational has arguments ['self', 'units', 'make_posterior_fn', 'make_prior_fn', 'kl_weight', 'kl_use_exact', 'activation', 'use_bias', 'activity_regularizer']
in `__init__` and therefore must override `get_config()`.
Example:
class CustomLayer(keras.layers.Layer):
    def __init__(self, arg1, arg2):
        super().__init__()
        self.arg1 = arg1
        self.arg2 = arg2

    def get_config(self):
        config = super().get_config()
        config.update({
            "arg1": self.arg1,
            "arg2": self.arg2,
        })
        return config
        
@fchollet Any advice how to save my model based on this code ?

**Comment by sachinprasadhs** [comment]
Please try to save the model in new `.keras` saving format, if your model is having custom objects, follow the below steps and use Keras 3 version.
https://keras.io/guides/serialization_and_saving/#custom-objects
