### ISSUE TITLE
Errors occur when I run the traffic forecasting example

### ISSUE THREAD

**Issue by Roy-NJU** [keras-team/keras-io#804]
The errors are as below:
2022-02-10 16:37:43.364454: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-02-10 16:37:43.524607: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2022-02-10 16:37:44.180079: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
 1/99 [..............................] - ETA: 3:08 - loss: 0.5246
 4/99 [>.............................] - ETA: 1s - loss: 0.8403  
 7/99 [=>............................] - ETA: 1s - loss: 0.8810
10/99 [==>...........................] - ETA: 1s - loss: 0.9521
13/99 [==>...........................] - ETA: 1s - loss: 0.9776
16/99 [===>..........................] - ETA: 1s - loss: 1.0086
19/99 [====>.........................] - ETA: 1s - loss: 1.0175
22/99 [=====>........................] - ETA: 1s - loss: 1.0118
25/99 [======>.......................] - ETA: 1s - loss: 0.9999
29/99 [=======>......................] - ETA: 1s - loss: 0.9852
33/99 [=========>....................] - ETA: 1s - loss: 0.9711
37/99 [==========>...................] - ETA: 1s - loss: 0.9590
40/99 [===========>..................] - ETA: 1s - loss: 0.9501
43/99 [============>.................] - ETA: 1s - loss: 0.9402
46/99 [============>.................] - ETA: 1s - loss: 0.9306
49/99 [=============>................] - ETA: 0s - loss: 0.9212
52/99 [==============>...............] - ETA: 0s - loss: 0.9115
56/99 [===============>..............] - ETA: 0s - loss: 0.8992
60/99 [=================>............] - ETA: 0s - loss: 0.8880
64/99 [==================>...........] - ETA: 0s - loss: 0.8770
67/99 [===================>..........] - ETA: 0s - loss: 0.8689
70/99 [====================>.........] - ETA: 0s - loss: 0.8607Traceback (most recent call last):
  File "D:/RNN-Models/keras-io-master/examples/timeseries/timeseries_traffic_forecasting.py", line 619, in <module>
    model.fit(
  File "C:\Users\lugongzheng\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\lugongzheng\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\lugongzheng\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 855, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "C:\Users\lugongzheng\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2942, in __call__
    return graph_function._call_flat(
  File "C:\Users\lugongzheng\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1918, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\lugongzheng\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 555, in call
    outputs = execute.execute(
  File "C:\Users\lugongzheng\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Input to reshape is a tensor with 312000 values, but the requested shape has 399360
	 [[node model/lstmgc/Reshape (defined at D:/RNN-Models/keras-io-master/examples/timeseries/timeseries_traffic_forecasting.py:569) ]] [Op:__inference_train_function_2162]

Errors may have originated from an input operation.
Input Source operations connected to node model/lstmgc/Reshape:
 model/lstmgc/graph_conv/concat (defined at D:/RNN-Models/keras-io-master/examples/timeseries/timeseries_traffic_forecasting.py:476)

Function call stack:
train_function

2022-02-10 16:37:45.930685: W tensorflow/core/kernels/data/cache_dataset_ops.cc:757] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Comment by SuryanarayanaY** [comment]
Hi @Roy-NJU ,

I have tested the tutorial with both CPU and GPU run times and there is no reported error now. Please refer to attached [cpu](https://colab.sandbox.google.com/gist/SuryanarayanaY/bcd960607bcb1f0e13fbbe965c34a679/kerasio_804-cpu-timeseries_traffic_forecasting.ipynb) and [gpu](https://colab.sandbox.google.com/gist/SuryanarayanaY/b555b8322ccd13b38fd1f3e6873eb1b1/kerasio_804-gpu-timeseries_traffic_forecasting.ipynb) gists for same.

Please verify and feel free to close the issue if resolved. Let us know if otherwise. Thanks!
